/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.quanlycoquannhanuoc.app.ui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nitro 5
 */
public class MainForm extends javax.swing.JFrame {
    private QuanLyNhanVienBienChePanel mquanlynhanvienbienche;
    private QuanLyNhanVienHopDongPanel mquanlynhanvienhopdong;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        Login dialog = new Login(this, true);
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        buttonQuanLyNhanViienBienChe = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        buttonQuanLyNhanVienHopDong = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tplMainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        tbrLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExitMainBoard = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuQuanLyNhanVienBienChe = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuQuanLyNhanVienHopDong = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        buttonQuanLyNhanViienBienChe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/Person-Male-Light-icon-24.png"))); // NOI18N
        buttonQuanLyNhanViienBienChe.setText("Quản Lý NV Biên Chế");
        buttonQuanLyNhanViienBienChe.setFocusable(false);
        buttonQuanLyNhanViienBienChe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonQuanLyNhanViienBienChe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonQuanLyNhanViienBienChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuanLyNhanViienBienCheActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonQuanLyNhanViienBienChe);
        jToolBar1.add(jSeparator5);

        buttonQuanLyNhanVienHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/man-icon (1).png"))); // NOI18N
        buttonQuanLyNhanVienHopDong.setText("Quản Lý NV Hợp Đòng");
        buttonQuanLyNhanVienHopDong.setFocusable(false);
        buttonQuanLyNhanVienHopDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonQuanLyNhanVienHopDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonQuanLyNhanVienHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuanLyNhanVienHopDongActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonQuanLyNhanVienHopDong);
        jToolBar1.add(jSeparator4);

        jMenu1.setText("Hệ Thống");

        tbrLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/Log-Out-icon_1.png"))); // NOI18N
        tbrLogout.setText("Đăng Xuất");
        tbrLogout.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        tbrLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(tbrLogout);
        jMenu1.add(jSeparator1);

        mnuExitMainBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/Actions-application-exit-icon.png"))); // NOI18N
        mnuExitMainBoard.setText("Thoát");
        mnuExitMainBoard.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mnuExitMainBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitMainBoardActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExitMainBoard);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        mnuQuanLyNhanVienBienChe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/Person-Male-Light-icon-16.png"))); // NOI18N
        mnuQuanLyNhanVienBienChe.setText("Quản Lý Nhân Viên Biên Chế");
        mnuQuanLyNhanVienBienChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuanLyNhanVienBienCheActionPerformed(evt);
            }
        });
        jMenu2.add(mnuQuanLyNhanVienBienChe);
        jMenu2.add(jSeparator2);

        mnuQuanLyNhanVienHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/man-icon.png"))); // NOI18N
        mnuQuanLyNhanVienHopDong.setText("Quản Lý Nhân Viên Hợp Đồng");
        mnuQuanLyNhanVienHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuanLyNhanVienHopDongActionPerformed(evt);
            }
        });
        jMenu2.add(mnuQuanLyNhanVienHopDong);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tplMainBoard)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuQuanLyNhanVienBienCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuanLyNhanVienBienCheActionPerformed
    if(mquanlynhanvienbienche == null){
       mquanlynhanvienbienche = new QuanLyNhanVienBienChePanel();
       ImageIcon icon = new ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/Person-Male-Light-icon-16.png"));
       tplMainBoard.addTab("Quản Lý Nhân Viên Biên Chế ", icon, mquanlynhanvienbienche,"Quản Lý Nhân Viên Biên Chế");
       }
       tplMainBoard.setSelectedComponent(mquanlynhanvienbienche);
    }//GEN-LAST:event_mnuQuanLyNhanVienBienCheActionPerformed

    private void tbrLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLogoutActionPerformed
           Login logindialog = new Login(this, true);
           logindialog.setVisible(true);
    }//GEN-LAST:event_tbrLogoutActionPerformed

    private void mnuExitMainBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitMainBoardActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitMainBoardActionPerformed

    private void mnuQuanLyNhanVienHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuanLyNhanVienHopDongActionPerformed
    if(mquanlynhanvienhopdong == null){
       mquanlynhanvienhopdong = new QuanLyNhanVienHopDongPanel();
       ImageIcon icon = new ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/man-icon.png"));
       tplMainBoard.addTab("Quản Lý Nhân Viên Hợp Đồng ", icon, mquanlynhanvienhopdong,"Quản Lý Nhân Viên Hợp Đồng");
       }
       tplMainBoard.setSelectedComponent(mquanlynhanvienhopdong);        
    }//GEN-LAST:event_mnuQuanLyNhanVienHopDongActionPerformed

    private void buttonQuanLyNhanViienBienCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuanLyNhanViienBienCheActionPerformed
    if(mquanlynhanvienbienche == null){
       mquanlynhanvienbienche = new QuanLyNhanVienBienChePanel();
       ImageIcon icon = new ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/Person-Male-Light-icon-16.png"));
       tplMainBoard.addTab("Quản Lý Nhân Viên Biên Chế ", icon, mquanlynhanvienbienche,"Quản Lý Nhân Viên Biên Chế");
       }
       tplMainBoard.setSelectedComponent(mquanlynhanvienbienche);
    }//GEN-LAST:event_buttonQuanLyNhanViienBienCheActionPerformed

    private void buttonQuanLyNhanVienHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuanLyNhanVienHopDongActionPerformed
    if(mquanlynhanvienhopdong == null){
       mquanlynhanvienhopdong = new QuanLyNhanVienHopDongPanel();
       ImageIcon icon = new ImageIcon(getClass().getResource("/oop/quanlycoquannhanuoc/app/icons/man-icon.png"));
       tplMainBoard.addTab("Quản Lý Nhân Viên Hợp Đồng ", icon, mquanlynhanvienhopdong,"Quản Lý Nhân Viên Hợp Đồng");
       }
       tplMainBoard.setSelectedComponent(mquanlynhanvienhopdong); 
    }//GEN-LAST:event_buttonQuanLyNhanVienHopDongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonQuanLyNhanVienHopDong;
    private javax.swing.JButton buttonQuanLyNhanViienBienChe;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuExitMainBoard;
    private javax.swing.JMenuItem mnuQuanLyNhanVienBienChe;
    private javax.swing.JMenuItem mnuQuanLyNhanVienHopDong;
    private javax.swing.JMenuItem tbrLogout;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
